# Generated by Django 3.2.7 on 2021-09-22 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineProjectApproval', '0002_auto_20210922_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('UserId', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Rollno', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=150)),
                ('Mobile', models.IntegerField(max_length=12)),
                ('Password', models.CharField(max_length=50)),
                ('Question', models.CharField(max_length=100)),
                ('Answer', models.CharField(max_length=50)),
                ('Pic', models.FileField(upload_to='media/images')),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineProjectApproval.branch')),
            ],
        ),
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=100)),
                ('Objective', models.CharField(max_length=1000)),
                ('Status', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineProjectApproval.branch')),
                ('Rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineProjectApproval.student')),
            ],
        ),
        migrations.CreateModel(
            name='TEACHER',
            fields=[
                ('UserId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=150)),
                ('Mobile', models.IntegerField(max_length=12)),
                ('Password', models.CharField(max_length=50)),
                ('Question', models.CharField(max_length=100)),
                ('Answer', models.CharField(max_length=50)),
                ('Pic', models.FileField(upload_to='media/images')),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineProjectApproval.branch')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=100)),
                ('Objective', models.CharField(max_length=1000)),
                ('File', models.FileField(upload_to='media/projects')),
                ('Status', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineProjectApproval.branch')),
                ('Rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineProjectApproval.student')),
            ],
        ),
        migrations.CreateModel(
            name='prevprojects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('File', models.FileField(upload_to='media/prev_projects')),
                ('Date', models.DateField()),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineProjectApproval.branch')),
            ],
        ),
    ]
