# Generated by Django 3.2.7 on 2021-09-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineProjectApproval', '0003_prevprojects_project_student_teacher_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Mobile',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='Rollno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Mobile',
            field=models.IntegerField(default=None),
        ),
    ]
