# Generated by Django 3.2.7 on 2021-09-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineProjectApproval', '0004_auto_20210922_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Mobile',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='Rollno',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Mobile',
            field=models.BigIntegerField(default=None),
        ),
    ]
