# Generated by Django 3.2.7 on 2021-09-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineProjectApproval', '0005_auto_20210922_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevprojects',
            name='File',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='File',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='Pic',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Pic',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
