# Generated by Django 3.2.7 on 2021-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineProjectApproval', '0006_auto_20210922_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Mobile',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Mobile',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
