# Generated by Django 3.2.7 on 2021-09-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineProjectApproval', '0007_auto_20210922_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
