# Generated by Django 3.2.7 on 2021-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineProjectApproval', '0009_auto_20210925_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevprojects',
            name='File',
            field=models.FileField(upload_to='prev_projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='File',
            field=models.FileField(upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Pic',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Pic',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
