# Generated by Django 3.2.7 on 2021-09-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineProjectApproval', '0010_auto_20210925_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Pic',
            field=models.FileField(default='default/profile.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Pic',
            field=models.FileField(default='default/profile.jpg', null=True, upload_to='images'),
        ),
    ]
