# Generated by Django 3.2.7 on 2021-09-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineProjectApproval', '0011_auto_20210925_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Pic',
            field=models.FileField(default='profile.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Pic',
            field=models.FileField(default='profile.jpg', upload_to='images'),
        ),
    ]
