# Generated by Django 3.2.7 on 2021-09-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineProjectApproval', '0012_auto_20210927_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Rollno',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
