# Generated by Django 3.2.7 on 2021-09-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineProjectApproval', '0013_alter_student_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='Ocomment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='Sdelete',
            field=models.CharField(default='OFF', max_length=3),
        ),
        migrations.AddField(
            model_name='title',
            name='Tcomment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='Tdelete',
            field=models.CharField(default='OFF', max_length=3),
        ),
    ]
