# Generated by Django 3.2.7 on 2021-09-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineProjectApproval', '0014_auto_20210929_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Comment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Sdelete',
            field=models.CharField(default='OFF', max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='Tdelete',
            field=models.CharField(default='OFF', max_length=3),
        ),
    ]
