# Generated by Django 3.2.8 on 2021-11-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineProjectApproval', '0015_auto_20210930_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Pic',
            field=models.FileField(default='images/profile.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Pic',
            field=models.FileField(default='images/profile.jpg', upload_to='images'),
        ),
    ]
