# Generated by Django 3.2.9 on 2021-12-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineProjectApproval', '0016_auto_20211106_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='chatfile',
            field=models.CharField(default='file', max_length=100),
        ),
    ]
